// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dH8pQ9a5UZL_OLgFufYCiCeOTaU8b5A',
    appId: '1:218660413688:web:5d73717d39ae2530079b0d',
    messagingSenderId: '218660413688',
    projectId: 'knocklogs',
    authDomain: 'knocklogs.firebaseapp.com',
    storageBucket: 'knocklogs.firebasestorage.app',
    measurementId: 'G-GE3M3HL24J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjOy2uBUWfvbe_dpHPvWMJ_svQbzPw1gY',
    appId: '1:218660413688:android:bf6babdfad256463079b0d',
    messagingSenderId: '218660413688',
    projectId: 'knocklogs',
    storageBucket: 'knocklogs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_D45-rJ37rDbQXIcvVRkDvdfvnjnylV4',
    appId: '1:218660413688:ios:9cb4916b3e7e803b079b0d',
    messagingSenderId: '218660413688',
    projectId: 'knocklogs',
    storageBucket: 'knocklogs.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_D45-rJ37rDbQXIcvVRkDvdfvnjnylV4',
    appId: '1:218660413688:ios:9cb4916b3e7e803b079b0d',
    messagingSenderId: '218660413688',
    projectId: 'knocklogs',
    storageBucket: 'knocklogs.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8dH8pQ9a5UZL_OLgFufYCiCeOTaU8b5A',
    appId: '1:218660413688:web:4f37c9bad463fce1079b0d',
    messagingSenderId: '218660413688',
    projectId: 'knocklogs',
    authDomain: 'knocklogs.firebaseapp.com',
    storageBucket: 'knocklogs.firebasestorage.app',
    measurementId: 'G-YTC2W2PEJM',
  );

}